Shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from Shop.settings import MEDIA_ROOT
from django.conf import settings

from goods.views import IndexView
from viewsCount.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # 文件上传处理函数
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('mdeditor/', include('mdeditor.urls')),
    path('goods/', include('goods.urls', namespace='goods')),
    path('company/', include('other.urls', namespace='company')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('viewscount.html', ViewsCount.as_view(), name='ViewsCount'),
    path('viewsCount/', include('viewsCount.urls', namespace='viewsCount'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = '伊特纳(天津)科技发展有限公司'
admin.site.site_title = '伊特纳(天津)科技发展有限公司后台管理'

apps/goods/urls.py
from django.urls import path

from .views import GoodsDetail, ProductsList, Search, AddMessage

app_name = 'goods'
urlpatterns = [
    path('goods_detail<int:goods_id>.html', GoodsDetail.as_view(), name='goods-detail'),
    path('products.html', ProductsList.as_view(), name='ProductsList'),
    path('search.html', Search.as_view(), name='Search'),
    path('message.html', AddMessage.as_view(), name='AddMessage'),

]

apps/other/urls.py
from django.urls import path

from .views import CompanyIntroduction_view, Factory_view, Customer_view, Video_view, News_view, News_detail, ContactView

app_name = 'company'
urlpatterns = [
    path('about.html', CompanyIntroduction_view.as_view(), name='CompanyIntroduction'),
    path('video.html', Video_view.as_view(), name='Video'),
    path('factory.html', Factory_view.as_view(), name='Factory'),
    path('customer.html', Customer_view.as_view(), name='Customer'),
    path('news.html', News_view.as_view(), name='News'),
    path('news<int:news_id>.html', News_detail.as_view(), name='NewsDetail'),
    path('contact.html', ContactView.as_view(), name='contact')
]

apps/other/models.py
from datetime import datetime
from django.db import models
from mdeditor.fields import MDTextField


# Create your models here.

class News(models.Model):
    '''
    新闻
    '''
    title = models.CharField(max_length=1000, help_text='新闻标题', blank=True, verbose_name='新闻标题')
    image = models.ImageField(upload_to='news/image', verbose_name='封面图片')
    detail = MDTextField(verbose_name='新闻详情', blank=True)
    add_time = models.DateField(default=datetime.now, verbose_name='发布时间')

    class Meta:
        verbose_name = '新闻'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class CompanyIntroduction(models.Model):
    '''
    公司信息
    '''
    name = models.CharField(max_length=100, verbose_name='公司名称', blank=True)
    summary = models.CharField(max_length=250, default='', verbose_name='公司摘要')
    detail = MDTextField(verbose_name='详细信息')
    addr = models.CharField(max_length=200, default='', verbose_name='公司地址', blank=True, null=True)
    tel = models.CharField(max_length=20, default='', verbose_name='公司电话', blank=True, null=True)
    email = models.EmailField(default='', verbose_name='公司邮箱', blank=True, null=True)
    web = models.CharField(max_length=50, default='', verbose_name='公司网站', blank=True, null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='发布时间')

    class Meta:
        verbose_name = '公司信息'
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        import re
        # 从 detail 摘取前 250 个字符赋给到 summary
        # summary = re.sub(' ', '', self.detail)
        summary = re.sub('#', '', self.detail)
        self.summary = summary[:250]

        # 调用父类的 save 方法将数据保存到数据库中
        super(CompanyIntroduction, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Factory(models.Model):
    '''
    工厂信息
    '''
    title = models.CharField(max_length=1000, help_text='厂名', verbose_name='厂名')
    image = models.ImageField(upload_to='factory/image', verbose_name='图片', )

    class Meta:
        verbose_name = '工厂信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Customer(models.Model):
    '''
    宣传客户
    '''
    title = models.CharField(max_length=1000, help_text='标题', verbose_name='标题')
    image = models.ImageField(upload_to='customer/image', verbose_name='图片', )

    class Meta:
        verbose_name = '宣传客户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Index(models.Model):
    '''
    首页关键词
    '''
    title = models.CharField(max_length=100, verbose_name='title', default='', )
    keywords = models.CharField(max_length=100, verbose_name='keywords', default='', )
    description = models.CharField(max_length=100, verbose_name='description', default='', )

    class Meta:
        verbose_name = '首页关键词'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class UserContactInfo(models.Model):
    """
    用户联系信息
    """
    name = models.CharField(max_length=100, verbose_name='昵称', default='')
    phone = models.CharField(max_length=100, blank=True, null=True, verbose_name='联系电话', default='')
    email = models.EmailField(max_length=100, verbose_name='邮箱', default='')
    country = models.CharField(max_length=100, verbose_name='国家', default='')
    message = models.TextField(verbose_name='联系内容', default='', )
    add_time = models.DateTimeField(default=datetime.now, verbose_name='联系时间')

    class Meta:
        verbose_name = '联系我们'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name + self.country + '，发起了联系'


class PageInformation(models.Model):
    product_info = MDTextField(verbose_name='产品页描述', default='')
    video_info = MDTextField(verbose_name='视频页描述', default='')
    customer_info = MDTextField(verbose_name='顾客页描述', default='')
    factory_info = MDTextField(verbose_name='工厂页描述', default='')
    news_info = MDTextField(verbose_name='新闻页描述', default='')

    class Meta:
        verbose_name = '页面信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.product_info


class Brands(models.Model):
    """
    品牌信息
    """
    name = models.CharField(max_length=30, verbose_name='品牌名称', default='')
    desc = models.CharField(max_length=200, verbose_name='品牌描述', default='', null=True, blank=True)
    url = models.URLField(verbose_name='品牌链接', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='联系时间')

    class Meta:
        verbose_name = '品牌信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/other/views.py
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from pure_pagination import Paginator, PageNotAnInteger
from django.views import View
from goods.views import Video, GoodsSeries
from django.core.cache import cache
from django.conf import settings

from viewsCount.tasks import send_contact_email
from .models import *
import markdown


# Create your views here.


class CompanyIntroduction_view(View):
    def get(self, request):
        company_info = cache.get('company_info')
        all_series = GoodsSeries.objects.all()
        all_brands = Brands.objects.all()
        if not company_info:
            company_info = CompanyIntroduction.objects.last()
            cache.set('company_info', company_info, settings.CUBES_REDIS_TIMEOUT)
        company_info.detail = markdown.markdown(company_info.detail.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'CompanyIntroduction', 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/CompanyIntroduction.html', {
            'company_info': company_info,
            'index_info': index_info,
            'all_series': all_series,
            'all_brands': all_brands,
        })


class Video_view(View):
    def get(self, request):
        video_info = PageInformation.objects.last()
        all_series = GoodsSeries.objects.all()
        all_brands = Brands.objects.all()
        com_info = CompanyIntroduction.objects.last()
        video_info = markdown.markdown(video_info.video_info.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        videos = cache.get('all_videos')
        if not videos:
            videos = Video.objects.all()
            cache.set('all_videos', videos, settings.CUBES_REDIS_TIMEOUT)
        p = Paginator(videos, request=request, per_page=3)
        videos = p.page(page)
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'Video', 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/Video.html', {
            'videos': videos,
            'index_info': index_info,
            'video_info': video_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,
        })


class Factory_view(View):
    def get(self, request):
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        page_info = PageInformation.objects.last()
        page_info = markdown.markdown(page_info.factory_info.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        all_brands = Brands.objects.all()
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        all_factory = cache.get('all_factory')
        if not all_factory:
            all_factory = Factory.objects.all()
            cache.set('all_factory', all_factory, settings.CUBES_REDIS_TIMEOUT)
        p = Paginator(all_factory, request=request, per_page=3)
        all_factory = p.page(page)
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'Factory', 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/Factory.html', {
            'all_factory': all_factory,
            'index_info': index_info,
            'page_info': page_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,

        })


class Customer_view(View):
    def get(self, request):
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        page_info = PageInformation.objects.last()
        page_info = markdown.markdown(page_info.customer_info.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        all_brands = Brands.objects.all()

        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        all_customer = cache.get('all_customer')
        if not all_customer:
            all_customer = Customer.objects.all()
            cache.set('all_customer', all_customer, settings.CUBES_REDIS_TIMEOUT)
        p = Paginator(all_customer, request=request, per_page=3)
        all_customer = p.page(page)
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'Customer', 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/Customer.html', {
            'all_customer': all_customer,
            'index_info': index_info,
            'page_info': page_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,
        })


class News_view(View):
    def get(self, request):
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        page_info = PageInformation.objects.last()
        page_info = markdown.markdown(page_info.news_info.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        all_brands = Brands.objects.all()
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        all_news = cache.get('all_news')
        if not all_news:
            all_news = News.objects.all()
            cache.set('all_news', all_news, settings.CUBES_REDIS_TIMEOUT)
        p = Paginator(all_news, request=request, per_page=3)
        all_news = p.page(page)
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'News', 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/NEWS.html', {
            'all_news': all_news,
            'index_info': index_info,
            'page_info': page_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,
        })


class News_detail(View):
    def get(self, request, news_id):
        news = cache.get('news_%s' % news_id)
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        all_brands = Brands.objects.all()
        if not news:
            news = News.objects.get(id=int(news_id))
            cache.set('news_%s' % news_id, news, settings.CUBES_REDIS_TIMEOUT)
        pnews = cache.get('news_%s' % (int(news_id) - 1))
        if not news:
            pnews = News.objects.get(id=int(news_id) - 1)
            cache.set('news_%s' % (int(news_id) - 1), pnews, settings.CUBES_REDIS_TIMEOUT)
        nnews = cache.get('news_%s' % (int(news_id) + 1))
        if not news:
            nnews = News.objects.get(id=int(news_id) + 1)
            cache.set('news_%s' % (int(news_id) + 1), nnews, settings.CUBES_REDIS_TIMEOUT)
        news.detail = markdown.markdown(news.detail.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'News:%s' % news.title, 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'other/NEWS_detail.html', {
            'pnews': pnews,
            'news': news,
            'nnews': nnews,
            'index_info': index_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,
        })


class ContactView(View):
    """
    联系我们
    """

    def get(self, request):
        all_series = GoodsSeries.objects.all()
        com_message = CompanyIntroduction.objects.last()
        all_brands = Brands.objects.all()
        return render(request, 'contact.html', {
            'com_message': com_message,
            'all_series': all_series,
            'all_brands': all_brands,
        })

    @csrf_exempt
    def post(self, request):
        data = dict()
        data['name'] = request.POST.get('name', None)
        data['phone'] = request.POST.get('phone', None)
        data['email'] = request.POST.get('email', None)
        data['country'] = request.POST.get('country', None)
        data['message'] = request.POST.get('message', None)
        send_contact_email.delay(data)

templates/other/NEWS.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{{ index_info.title }}{% endblock %}
{% block description %}{{ index_info.description }}{% endblock %}
{% block keywords %}{{ index_info.keywords }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
    <body class="single is-preload">
{% endblock %}
{% block content-index %}
    <div id="heard-photo" class="heard-photo"></div>
    <div class="sidebar">
        <div class="container">
            <ul>
                <li class="active">
                    <a href="#">{% trans 'Company News' %}</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="wrap wrap-news">
        <div class="container">
            <div class="title-in">
                <h2>{% trans 'News' %}</h2>
                <p>{{ page_info|safe }}</p>
            </div>

            <div class="row waterfall">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 padding">
                    {% for news in all_news.object_list %}
                        <div class="item">
                            <div class="pic">
                                <a href="{% url 'company:NewsDetail' news.id %}">
                                    <img src="{{ MEDIA_URL }}{{ news.image }}"
                                         style="display: inline;">
                                </a>
                                <a class="date" href="#">
                                    {{ news.add_time }}
                                </a>
                            </div>
                            <div class="note">
                                <h3><a href="{% url 'company:NewsDetail' news.id %}"
                                       title="{{ news.title }}">{{ news.title }}</a>
                                </h3>
                                <p><a href="{% url 'company:NewsDetail' news.id %}"></a></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
        <ul class="pager">
            {% if all_news.has_previous %}
                <li><a href="?{{ all_news.previous_page_number.querystring }}">&laquo;{% trans 'PREVIOUS PAGE' %}</a>
                </li>
            {% else %}
                <li><a class="disabled"><span>&laquo;{% trans 'PREVIOUS PAGE' %}</span></a></li>
            {% endif %}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if all_news.has_next %}
                <li><a href="?{{ all_news.next_page_number.querystring }}">{% trans 'NEXT PAGE' %}&raquo;</a></li>
            {% else %}
                <li><a class="disabled"><span>{% trans 'NEXT PAGE' %}&raquo;</span></a></li>
            {% endif %}
        </ul>
    </div>
    <style>
        #footer .links a {
            display: block !important;
            color: #7e7e7e;
        }
    </style>
    <div id="footer-wrapper"
         style="width: 100%;padding: 40px 60px 40px 60px;background-color: #303030;text-decoration: none;">
        <footer id="footer" class="">
            <div class="row">
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">ABOUT US</h3>
                        <a href="{% url 'company:CompanyIntroduction' %}">Company Introduction</a>
                        <a href="{% url 'company:Factory' %}">Factory</a>
                        <a href="{% url 'company:Video' %}">Video</a>
                        <a href="{% url 'company:Customer' %}">Customer</a>
                    </section>
                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">PRODUCT</h3>
                        {% for i in all_series %}
                            <a href="{% url 'goods:ProductsList' %}?sid={{ i.id }}">{{ i.name }}</a>

                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">OUR BRANDS</h3>
                        {% for i in all_brands %}
                            <a href="http://{{ i.url }}">{{ i.name }}</a>
                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Contact -->
                    <section class="widget links">
                        <h3 style="color: white;">CONTACT</h3>
                        <ul class="icons">
                            <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                            <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                        </ul>

                        <span style="color: white;">Tel:&nbsp;
                            <a>{{ com_info.tel }}</a>
                        </span>
                        <span style="color: white;">Email:&nbsp;
                             <a href="mailto:{{ com_info.email }}">{{ com_info.email }}</a>
                        </span>
                        <span style="color: white;">Website:&nbsp;
                            <a href="http://{{ com_info.web }}">{{ com_info.web }}</a>
                        </span>
                        <span style="color: white;">Address:&nbsp;</span>
                        <p style="color: #7e7e7e;">{{ com_info.addr }}</p>
                    </section>

                </div>
            </div>

        </footer>
        <br><br><br>
        <div style="text-align: center;color: white;padding: auto auto;">
            <span class="copyright">
                &copy; 2019-2029.Tianjin Eternal Science and Technology Development Co. LTD.All rights reserved.
            </span>
        </div>
    </div>

{% endblock %}
{% block left-content %}


{% endblock %}


{% block js %}
    <script>
        $(function () {
            $('.change_language').change(function (e) {
                e.preventDefault();
                $('#change_form').submit();
                return false;
            });
        })
    </script>
    <script src="{% static 'js/main_.js' %}"></script>
{% endblock %}

templates/other/NEWS_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{{ index_info.title }}{% endblock %}
{% block description %}{{ index_info.description }}{% endblock %}
{% block keywords %}{{ index_info.keywords }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
    <body class="single is-preload">
{% endblock %}
{% block content-index %}
    <div id="heard-photo" class="heard-photo"></div>
    <div class="sidebar">
        <div class="container">
            <ul>
                <li class="active">
                    <a href="#">{% trans 'Company News' %}</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="wrap wrap-news-show">
        <div class="container">
            <div class="news-title">
                <h3>
                    {{ news.title }}
                </h3>
                <span>
                    {{ news.add_time }}
                </span>
            </div>

            <p class="text">
                {{ news.detail|safe }}
            </p>

            <ul class="pager">
                {% if pnews %}
                    <li class="previous"><a href="{% url 'company:NewsDetail' pnews.id %}">&laquo;{{ pnews.title }}</a>
                    </li>
                {% endif %}
                {% if nnews %}
                    <li class="next"><a href="{% url 'company:NewsDetail' nnews.id %}">{{ nnews.title }}&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <style>
        #footer .links a {
            display: block !important;
            color: #7e7e7e;
        }
    </style>
    <div id="footer-wrapper"
         style="width: 100%;padding: 40px 60px 40px 60px;background-color: #303030;text-decoration: none;margin: 60px 0 0 0;">
        <footer id="footer" class="">
            <div class="row">
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">ABOUT US</h3>
                        <a href="{% url 'company:CompanyIntroduction' %}">Company Introduction</a>
                        <a href="{% url 'company:Factory' %}">Factory</a>
                        <a href="{% url 'company:Video' %}">Video</a>
                        <a href="{% url 'company:Customer' %}">Customer</a>
                    </section>
                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">PRODUCT</h3>
                        {% for i in all_series %}
                            <a href="{% url 'goods:ProductsList' %}?sid={{ i.id }}">{{ i.name }}</a>

                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">OUR BRANDS</h3>
                        {% for i in all_brands %}
                            <a href="http://{{ i.url }}">{{ i.name }}</a>
                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Contact -->
                    <section class="widget links">
                        <h3 style="color: white;">CONTACT</h3>
                        <ul class="icons">
                            <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                            <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                        </ul>

                        <span style="color: white;">Tel:&nbsp;
                            <a>{{ com_info.tel }}</a>
                        </span>
                        <span style="color: white;">Email:&nbsp;
                             <a href="mailto:{{ com_info.email }}">{{ com_info.email }}</a>
                        </span>
                        <span style="color: white;">Website:&nbsp;
                            <a href="http://{{ com_info.web }}">{{ com_info.web }}</a>
                        </span>
                        <span style="color: white;">Address:&nbsp;</span>
                        <p style="color: #7e7e7e;">{{ com_info.addr }}</p>
                    </section>

                </div>
            </div>

        </footer>
        <br><br><br>
        <div style="text-align: center;color: white;padding: auto auto;">
            <span class="copyright">
                &copy; 2019-2029.Tianjin Eternal Science and Technology Development Co. LTD.All rights reserved.
            </span>
        </div>
    </div>

{% endblock %}
{% block left-content %}


{% endblock %}


{% block js %}
    <script>
        $(function () {
            $('.change_language').change(function (e) {
                e.preventDefault();
                $('#change_form').submit();
                return false;
            });
        })
    </script>
    <script src="{% static 'js/main_.js' %}"></script>
{% endblock %}