Shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from Shop.settings import MEDIA_ROOT
from django.conf import settings

from goods.views import IndexView
from viewsCount.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # 文件上传处理函数
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('mdeditor/', include('mdeditor.urls')),
    path('goods/', include('goods.urls', namespace='goods')),
    path('company/', include('other.urls', namespace='company')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('viewscount.html', ViewsCount.as_view(), name='ViewsCount'),
    path('viewsCount/', include('viewsCount.urls', namespace='viewsCount'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = '伊特纳(天津)科技发展有限公司'
admin.site.site_title = '伊特纳(天津)科技发展有限公司后台管理'

apps/goods/urls.py
from django.urls import path

from .views import GoodsDetail, ProductsList, Search, AddMessage

app_name = 'goods'
urlpatterns = [
    path('goods_detail<int:goods_id>.html', GoodsDetail.as_view(), name='goods-detail'),
    path('products.html', ProductsList.as_view(), name='ProductsList'),
    path('search.html', Search.as_view(), name='Search'),
    path('message.html', AddMessage.as_view(), name='AddMessage'),

]

apps/other/urls.py
from django.urls import path

from .views import CompanyIntroduction_view, Factory_view, Customer_view, Video_view, News_view, News_detail, ContactView

app_name = 'company'
urlpatterns = [
    path('about.html', CompanyIntroduction_view.as_view(), name='CompanyIntroduction'),
    path('video.html', Video_view.as_view(), name='Video'),
    path('factory.html', Factory_view.as_view(), name='Factory'),
    path('customer.html', Customer_view.as_view(), name='Customer'),
    path('news.html', News_view.as_view(), name='News'),
    path('news<int:news_id>.html', News_detail.as_view(), name='NewsDetail'),
    path('contact.html', ContactView.as_view(), name='contact')
]

apps/goods/models.py
from datetime import datetime

from django.db import models
from mdeditor.fields import MDTextField


# Create your models here.
class GoodsSeries(models.Model):
    '''
    商品系列
    '''
    name = models.CharField(max_length=50, unique=True, verbose_name='系列名', help_text='系列名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '商品系列'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# class GoodsCategory(models.Model):
#     """
#     商品分类
#     """
#     name = models.CharField(max_length=50, unique=True, verbose_name='类别名', help_text='类别名')
#     # series = models.ForeignKey(GoodsSeries, verbose_name='系列', on_delete=models.CASCADE)
#     add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
#
#     class Meta:
#         verbose_name = '商品分类'
#         verbose_name_plural = verbose_name
#
#     def __str__(self):
#         return self.name


class Goods(models.Model):
    """
    商品信息
    """
    series = models.ForeignKey(GoodsSeries, on_delete=models.CASCADE, verbose_name='商品系列', null=True)
    name = models.CharField(max_length=100, verbose_name='商品名', help_text='商品名')
    goods_sn = models.CharField(max_length=128, unique=True, verbose_name='商品编码')
    goods_front_img = models.ImageField(upload_to='goods/images', verbose_name='商品封面')
    desc = models.TextField(blank=True, verbose_name='商品描述', null=True)
    detail = MDTextField(verbose_name='商品详情', default='', blank=True, null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    attr = models.ManyToManyField('GoodsAttributes', related_name='goods', verbose_name='商品属性')
    title = models.CharField(max_length=100, blank=True, verbose_name='title', default='', null=True)
    keywords = models.CharField(max_length=100, blank=True, verbose_name='keywords', default='', null=True)
    description = models.CharField(max_length=100, blank=True, verbose_name='description', default='', null=True)
    leval = models.IntegerField(verbose_name='权重', default=0)

    class Meta:
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsImage(models.Model):
    """
    商品轮播图
    """
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='商品')
    image = models.ImageField(upload_to='goods/banner', verbose_name='商品轮播图')
    index = models.IntegerField(default=0, verbose_name='轮播顺序（第一个轮播图必须为0）')
    alt = models.CharField(max_length=100, verbose_name='图片alt', blank=True, null=True, )
    title = models.CharField(max_length=100, verbose_name='图片title', blank=True, null=True, )
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '商品轮播图'
        verbose_name_plural = verbose_name
        unique_together = ['goods', 'index']

    def __str__(self):
        return self.goods.name


class Banner(models.Model):
    """
    首页轮播图
    """
    title = models.CharField(default='', max_length=128, verbose_name='标题')
    image = models.ImageField(upload_to='banner', max_length=512, verbose_name='轮播图')
    url = models.URLField(max_length=256, verbose_name='访问地址', blank=True, null=True, )
    index = models.IntegerField(default=0, unique=True, verbose_name='轮播顺序（第一个轮播图必须为0）')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    alt = models.CharField(max_length=100, verbose_name='图片alt', blank=True, null=True)

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class GoodsAttributes(models.Model):
    '''
    商品属性
    '''
    name = models.CharField(max_length=100, verbose_name='属性名', help_text='属性名')
    weight = models.IntegerField(default=0, verbose_name='属性权重', help_text='属性权重')
    value = models.CharField(max_length=100, verbose_name='属性值', help_text='属性值')

    class Meta:
        verbose_name = '商品属性'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name + ":" + self.value


#  3-10

class Message(models.Model):
    '''
    留言板内容
    '''
    inquire = models.CharField(max_length=100, verbose_name='商品型号')
    name = models.CharField(max_length=100, verbose_name='游客', help_text='游客')
    phone = models.CharField(max_length=15, blank=True, verbose_name='手机号', help_text='手机号')
    email = models.EmailField(max_length=100, verbose_name='邮箱', blank=True, null=True)
    address = models.CharField(max_length=1000, verbose_name='地址', blank=True, null=True)
    message = models.TextField(verbose_name='留言')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='留言时间')

    class Meta:
        verbose_name = '留言板内容'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.message


class Video(models.Model):
    '''
    视频
    '''
    title = models.CharField(max_length=1000, help_text='视频标题', verbose_name='视频标题')
    video = models.FileField(upload_to='video/', verbose_name='视频(MP4、FLV)')
    image = models.CharField(default='none', max_length=512, null=True, verbose_name='封面(不用手动添加此项)', blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/goods/views.py
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.db.models import Q
from django.core.cache import cache
from .models import *
from pure_pagination import Paginator, PageNotAnInteger
import markdown
import json
from viewsCount.tasks import send_goods_email
from django.conf import settings
from other.models import Index, CompanyIntroduction, PageInformation, Brands


# Create your views here.


class IndexView(View):
    def get(self, request):
        all_goods = cache.get('all_goods')
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        all_brands = Brands.objects.all()
        if not all_goods:
            all_goods = Goods.objects.all().order_by('-leval')[:4]
            cache.set('all_goods', all_goods, settings.CUBES_REDIS_TIMEOUT)
        for goods in all_goods:
            goods.detail = markdown.markdown(goods.detail.replace("\r\n", '  \n'), extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ])
        for goods in all_goods:
            goods.goodsimage = list(goods.goodsimage_set.all())
        # all_category = cache.get('all_category')
        # if not all_category:
        #     all_category = GoodsCategory.objects.all()
        #     cache.set('all_category', all_category, settings.CUBES_REDIS_TIMEOUT)
        all_banner = cache.get('all_banner')
        if not all_banner:
            all_banner = Banner.objects.order_by('index')
            cache.set('all_banner', all_banner, settings.CUBES_REDIS_TIMEOUT)
        index_info = Index.objects.last()
        videos = Video.objects.all()
        if len(videos) >= 2:
            video1 = videos[len(videos) - 1]
            video2 = videos[len(videos) - 2]
        elif len(videos) == 1:
            video1 = videos[0]
            video2 = None
        else:
            video1 = None
            video2 = None
        return render(request, 'index.html', {
            # 'all_category': all_category,
            'all_goods': all_goods,
            'all_banner': all_banner,
            'index_info': index_info,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands,
            'video1': video1,
            'video2': video2,

        })


class GoodsDetail(View):
    def get(self, request, goods_id):
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.last()
        all_brands = Brands.objects.all()
        goods = cache.get('goods_%s' % goods_id)
        if not goods:
            goods = Goods.objects.filter(id=goods_id).first()
            cache.set('goods_%s' % goods_id, goods, settings.CUBES_REDIS_TIMEOUT)
        goods.detail = markdown.markdown(goods.detail.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        # current_category = cache.get('category_by_g%s' % goods_id)
        # if not current_category:
        #     current_category = goods.category
        #     cache.set('category_by_g%s' % goods_id, current_category, settings.CUBES_REDIS_TIMEOUT)
        # current_series = cache.get('series_by_c%s' % current_category.id)
        # if not current_series:
        #     current_series = current_category.series
        #     cache.set('series_by_c%s' % current_category.id, current_series, settings.CUBES_REDIS_TIMEOUT)
        current_series = cache.get('series_by_g%s' % goods_id)
        if not current_series:
            current_series = goods.series
            cache.set('series_by_g%s' % goods_id, current_series, settings.CUBES_REDIS_TIMEOUT)
        goods_banners = cache.get('goods_banners_%s' % goods_id)
        if not goods_banners:
            goods_banners = goods.goodsimage_set.all()
            cache.set('goods_banners_%s' % goods_id, goods_banners, settings.CUBES_REDIS_TIMEOUT)
        goods_attrs = cache.get('goods_attrs_%s' % goods_id)
        if not goods_attrs:
            goods_attrs = GoodsAttributes.objects.filter(goods__id=goods_id).all().order_by('-weight')[:3]
            cache.set('goods_attrs_%s' % goods_id, goods_attrs, settings.CUBES_REDIS_TIMEOUT)
        return render(request, 'goods/goods-detail.html', {
            'goods': goods,
            'goods_banners': goods_banners,
            'goods_attrs': goods_attrs,
            'sid': current_series.id,
            # 'cid': current_category.id,
            'sname': current_series.name,
            # 'cname': current_category.name,
            'all_series': all_series,
            'com_info': com_info,
            'all_brands': all_brands
        })


class ProductsList(View):
    def get(self, request):
        com_info = CompanyIntroduction.objects.last()
        page_info = PageInformation.objects.last()
        page_info = markdown.markdown(page_info.product_info.replace("\r\n", '  \n'), extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        all_brands = Brands.objects.all()
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        sid = request.GET.get('sid', None)
        # cid = request.GET.get('cid', None)
        series = cache.get('all_series')
        if not series:
            series = GoodsSeries.objects.all()
            cache.set('all_series', series, settings.CUBES_REDIS_TIMEOUT)
        # if cid and cid.isdigit():
        #     cid = int(cid)
        #     current_category = cache.get('category_%s' % cid)
        #     if not current_category:
        #         current_category = GoodsCategory.objects.filter(id=cid).first()
        #         cache.set('category_%s' % cid, current_category, settings.CUBES_REDIS_TIMEOUT)
        #     sid = current_category.series.id
        #     query = '%s-%s' % (current_category.series.name, current_category.name)
        #     categorys = cache.get('categorys_by_s%s' % sid)
        #     if not categorys:
        #         categorys = GoodsCategory.objects.filter(series__id=int(sid)).all()
        #         cache.set('categorys_by_s%s' % sid, categorys)
        #     goods_list = list(Goods.objects.filter(category__id=int(cid)).prefetch_related('goodsimage_set').order_by('-leval'))
        # elif sid and sid.isdigit():
        if sid and sid.isdigit():
            sid = int(sid)
            # categorys = cache.get('categorys_by_s%s' % sid)
            # if not categorys:
            #     categorys = GoodsCategory.objects.filter(series__id=int(sid)).all()
            #     cache.set('categorys_by_s%s' % sid, categorys, settings.CUBES_REDIS_TIMEOUT)
            # goods_list = []
            # for category in categorys:
            #     goods_list.extend(
            #         list(Goods.objects.filter(category__id=category.id).prefetch_related('goodsimage_set').order_by('-leval')))
            goods_list = Goods.objects.filter(series__id=sid).prefetch_related('goodsimage_set').order_by('-leval')
            query = GoodsSeries.objects.filter(id=sid).first().name
        else:
            # categorys = cache.get('all_category')
            # if not categorys:
            #     categorys = GoodsCategory.objects.all()
            #     cache.set('all_category', categorys, settings.CUBES_REDIS_TIMEOUT)
            # goods_list = []
            # for category in categorys:
            #     goods_list.extend(
            #         list(Goods.objects.filter(category__id=category.id).prefetch_related('goodsimage_set').order_by(
            #             '-leval')))
            # categorys = None
            series = cache.get('all_series')
            if not series:
                series = GoodsSeries.objects.all()
                cache.set('all_series', series, settings.CUBES_REDIS_TIMEOUT)
            goods_list = []
            for s in series:
                goods_list.extend(
                    list(Goods.objects.filter(series__id=s.id).prefetch_related('goodsimage_set').order_by(
                        '-leval')))
            sid = None
            # cid = None
            query = 'All'
        for goods in goods_list:
            goods.goodsimage = list(goods.goodsimage_set.all())
        p = Paginator(goods_list, request=request, per_page=5)
        goods_list = p.page(page)
        index_info = cache.get('index_info')
        if not index_info:
            index_info = Index.objects.last()
            cache.set('index_info', index_info)
        index_info = {'title': 'Products-%s' % query, 'description': index_info.description,
                      'keywords': index_info.keywords}
        return render(request, 'goods/products.html',
                      {
                          'sid': sid,
                          # 'cid': cid,
                          # 'categorys': categorys,
                          'all_series': series,
                          'goods_list': goods_list,
                          'index_info': index_info,
                          'page_info': page_info,
                          'com_info': com_info,
                          'all_brands': all_brands,
                      })


class Search(View):
    def get(self, request):
        all_series = GoodsSeries.objects.all()
        com_info = CompanyIntroduction.objects.get(pk=1)
        all_brands = Brands.objects.all()
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        query = request.GET.get('query', None)
        goods_list = []
        series = GoodsSeries.objects.filter(name__icontains=query).all()
        # categorys = []
        # for s in series:

templates/goods/products.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{{ index_info.title }}{% endblock %}
{% block description %}{{ index_info.description }}{% endblock %}
{% block keywords %}{{ index_info.keywords }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
    <body class="single is-preload">
{% endblock %}
{% block content-index %}
    <div id="heard-photo" class="heard-photo"></div>
    <div class="sidebar">
        <div class="container">
            <ul>
                <li>
                    <a href="#" style="width: 120px">{% trans 'Series' %}</a>
                </li>
                {% if sid %}
                    <li>
                        <a href="{% url 'goods:ProductsList' %}">{% trans 'All' %}</a>
                    </li>
                    {% for s in all_series %}
                        {% if sid == s.id %}
                            <li class="active">
                                <a href="{% url 'goods:ProductsList' %}?sid={{ s.id }}">{{ s.name }}</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'goods:ProductsList' %}?sid={{ s.id }}">{{ s.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <li class="active">
                        <a href="{% url 'goods:ProductsList' %}">{% trans 'All' %}</a>
                    </li>
                    {% for s in all_series %}
                        <li>
                            <a href="{% url 'goods:ProductsList' %}?sid={{ s.id }}">{{ s.name }}</a>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>

    </div>
    <div class="wrap wrap-product">
    <div class="container">
        <div class="title-in">
            <h2>{% trans 'Products' %}</h2>
            <p>{{ page_info|safe }}</p>
        </div>

        <div class="row">
            {% if not goods_list %}
                <h2>{% trans 'No Products' %}</h2>
            {% endif %}
            {% for goods in goods_list.object_list %}
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="item" style="background-color: rgb(246, 244, 236);">
                        <div class="p-title">
                            <h3>{{ goods.goods_sn }}</h3>
                            <p>{{ goods.name }}</p>
                        </div>
                        <div class="flexslider">
                            <div id="{{ goods.goods_sn }}" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    {% for image in goods.goodsimage %}
                                        {% if image.index == 0 %}
                                            <li data-target="#{{ goods.goods_sn }}"
                                                data-slide-to="{{ image.index }}" class="active"></li>
                                        {% else %}
                                            <li data-target="#{{ goods.goods_sn }}"
                                                data-slide-to="{{ image.index }}"></li>
                                        {% endif %}
                                    {% endfor %}
                                </ol>
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                    {% for image in goods.goodsimage %}
                                        {% if image.index == 0 %}
                                            <div class="item active">
                                                <a href="{% url 'goods:goods-detail' goods.id %}">
                                                    <img src="{{ MEDIA_URL }}{{ image.image }}" alt="" width="100%">
                                                </a>
                                            </div>
                                        {% else %}
                                            <div class="item">
                                                <a href="{% url 'goods:goods-detail' goods.id %}">
                                                    <img src="{{ MEDIA_URL }}{{ image.image }}" alt="" width="100%">
                                                </a>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <ul class="pager">
            {% if goods_list.has_previous %}
                <li><a href="?{{ goods_list.previous_page_number.querystring }}">&laquo;{% trans 'PREVIOUS PAGE' %}</a>
                </li>
            {% else %}
                <li><a class="disabled"><span>&laquo;{% trans 'PREVIOUS PAGE' %}</span></a></li>
            {% endif %}
            {% if goods_list.has_next %}
                <li><a href="?{{ goods_list.next_page_number.querystring }}">{% trans 'NEXT PAGE' %}&raquo;</a></li>
            {% else %}
                <li><a class="disabled"><span>{% trans 'NEXT PAGE' %}&raquo;</span></a></li>
            {% endif %}
        </ul>
    </div>
    <style>
        #footer .links a {
            display: block !important;
            color: #7e7e7e;
        }
    </style>


{% endblock %}

{% block left-content %}
    <div id="footer-wrapper"
         style="width: 100%;padding: 40px 60px 40px 60px;background-color: #303030;text-decoration: none;">
        <footer id="footer" class="">
            <div class="row">
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">ABOUT US</h3>
                        <a href="{% url 'company:CompanyIntroduction' %}">Company Introduction</a>
                        <a href="{% url 'company:Factory' %}">Factory</a>
                        <a href="{% url 'company:Video' %}">Video</a>
                        <a href="{% url 'company:Customer' %}">Customer</a>
                    </section>
                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">PRODUCT</h3>
                        {% for i in all_series %}
                            <a href="{% url 'goods:ProductsList' %}?sid={{ i.id }}">{{ i.name }}</a>

                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">
                    <!-- Links -->
                    <section class="widget links">
                        <h3 style="color: white;">OUR BRANDS</h3>
                        {% for i in all_brands %}
                            <a href="http://{{ i.url }}">{{ i.name }}</a>
                        {% endfor %}
                    </section>

                </div>
                <div class="col-3 col-6-medium col-12-small">

                    <!-- Contact -->
                    <section class="widget links">
                        <h3 style="color: white;">CONTACT</h3>
                        <ul class="icons">
                            <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                            <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                        </ul>

                        <span style="color: white;">Tel:&nbsp;
                            <a>{{ com_info.tel }}</a>
                        </span>
                        <span style="color: white;">Email:&nbsp;
                             <a href="mailto:{{ com_info.email }}">{{ com_info.email }}</a>
                        </span>
                        <span style="color: white;">Website:&nbsp;
                            <a href="http://{{ com_info.web }}">{{ com_info.web }}</a>
                        </span>
                        <span style="color: white;">Address:&nbsp;</span>
                        <p style="color: #7e7e7e;">{{ com_info.addr }}</p>
                    </section>

                </div>
            </div>

        </footer>
        <br><br><br>
        <div style="text-align: center;color: white;padding: auto auto;">
            <span class="copyright">
                &copy; 2019-2029.Tianjin Eternal Science and Technology Development Co. LTD.All rights reserved.
            </span>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            $('.change_language').change(function (e) {
                e.preventDefault();
                $('#change_form').submit();
                return false;
            });
        })
    </script>
    <script src="{% static 'js/main_.js' %}"></script>
{% endblock %}