Shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from Shop.settings import MEDIA_ROOT
from django.conf import settings

from goods.views import IndexView
from viewsCount.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # 文件上传处理函数
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('mdeditor/', include('mdeditor.urls')),
    path('goods/', include('goods.urls', namespace='goods')),
    path('company/', include('other.urls', namespace='company')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('viewscount.html', ViewsCount.as_view(), name='ViewsCount'),
    path('viewsCount/', include('viewsCount.urls', namespace='viewsCount'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = '伊特纳(天津)科技发展有限公司'
admin.site.site_title = '伊特纳(天津)科技发展有限公司后台管理'

apps/goods/urls.py
from django.urls import path

from .views import GoodsDetail, ProductsList, Search, AddMessage

app_name = 'goods'
urlpatterns = [
    path('goods_detail<int:goods_id>.html', GoodsDetail.as_view(), name='goods-detail'),
    path('products.html', ProductsList.as_view(), name='ProductsList'),
    path('search.html', Search.as_view(), name='Search'),
    path('message.html', AddMessage.as_view(), name='AddMessage'),

]

apps/other/urls.py
from django.urls import path

from .views import CompanyIntroduction_view, Factory_view, Customer_view, Video_view, News_view, News_detail, ContactView

app_name = 'company'
urlpatterns = [
    path('about.html', CompanyIntroduction_view.as_view(), name='CompanyIntroduction'),
    path('video.html', Video_view.as_view(), name='Video'),
    path('factory.html', Factory_view.as_view(), name='Factory'),
    path('customer.html', Customer_view.as_view(), name='Customer'),
    path('news.html', News_view.as_view(), name='News'),
    path('news<int:news_id>.html', News_detail.as_view(), name='NewsDetail'),
    path('contact.html', ContactView.as_view(), name='contact')
]

templates/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{% trans 'CONTACT US' %}{% endblock %}
{% block content-index %}
    <div id="main">
        <!-- Post -->
        <article class="post">
            <header>
                <div class="title" style="text-align: left">
                    <section>
                        <h2>{% trans 'Company Info' %}</h2><br>
                    </section>
                    <div style="color: orange;font-size: 24px;font-weight: bold;">{{ com_message.name }}</div>
                    <br>
                    <span style="font-size: 20px;color: #3c3c3c">{% trans 'Tel' %}:&nbsp;&nbsp;{{ com_message.tel }}</span><br>
                    <a href="mailto:{{ com_message.email }}"><span style="font-size: 20px;color: #3c3c3c">{% trans 'Email' %}:&nbsp;&nbsp;{{ com_message.email }}</span></a><br>
                    <span style="font-size: 20px;color: #3c3c3c">{% trans 'Website' %}:&nbsp;&nbsp;
                        <a href="https://www.baidu.com" style="text-decoration:none;">{{ com_message.web }}</a>
                    </span><br>
                    <span style="font-size: 20px;color: #3c3c3c">{% trans 'Address' %}:&nbsp;&nbsp;{{ com_message.addr }}</span>
                </div>
                <div class="meta">
                    <h3>{% trans 'Contact' %}</h3>
                    <img src="{% static 'images/com-logo.png' %}" alt=""/>
                </div>
            </header>

            <div class="note">
                <span style="font-size: 30px; font-weight: bold;">{% trans 'Leave us a message' %}</span><br><br><br>
                <form class="row feedback-form" onsubmit="return false;" method="post" id="jsForm">
                    {% csrf_token %}

                    <div class="col-xs-12 col-md-6 text">
                        <input type="text" placeholder="{% trans 'Name' %} *" name="name" id="name"
                               style="background-color: rgb(246, 244, 236);">
                    </div>
                    <div class="col-xs-12 col-md-6 text">
                        <input type="text" placeholder="{% trans 'Phone' %}" name="phone" id="phone"
                               style="background-color: rgb(246, 244, 236);">
                    </div>
                    <br><br><br>
                    <div class="col-xs-12 col-md-6 text">
                        <input type="text" placeholder="{% trans 'Email' %} *" name="email" id="email"
                               style="background-color: rgb(246, 244, 236);">
                    </div>
                    <div class="col-xs-12 col-md-6 text">
                        <input type="text" placeholder="{% trans 'Country' %} *" name="country" id="country"
                               style="background-color: rgb(246, 244, 236);">
                    </div>
                    <br><br><br>
                    <div class="col-xs-12">
                        <textarea name="message" rows="6" placeholder="{% trans 'Messages' %} *" id="message"
                                  style="background-color: rgb(246, 244, 236);"></textarea>
                    </div>
                    <p>* Required Field.</p>
                    <p class="errors" id="jsCompanyTips"></p>
                    <br><br><br>
                    <div class="col-xs-12">
                        <button class="send submit" id="jsBtn"><span>{% trans 'SUBMIT' %} </span></button>
                    </div>

                </form>
            </div>
        </article>
        <style>
            #footer .links a {
                display: block !important;
                color: #7e7e7e;
            }
        </style>
        <div id="footer-wrapper"
             style="width: 100%;padding: 40px 60px 40px 60px;background-color: #303030;text-decoration: none;">
            <footer id="footer" class="">
                <div class="row">
                    <div class="col-3 col-6-medium col-12-small">
                        <!-- Links -->
                        <section class="widget links">
                            <h3 style="color: white;">ABOUT US</h3>
                            <a href="{% url 'company:CompanyIntroduction' %}">Company Introduction</a>
                            <a href="{% url 'company:Factory' %}">Factory</a>
                            <a href="{% url 'company:Video' %}">Video</a>
                            <a href="{% url 'company:Customer' %}">Customer</a>
                        </section>
                    </div>
                    <div class="col-3 col-6-medium col-12-small">

                        <!-- Links -->
                        <section class="widget links">
                            <h3 style="color: white;">PRODUCT</h3>
                            {% for i in all_series %}
                                <a href="{% url 'goods:ProductsList' %}?sid={{ i.id }}">{{ i.name }}</a>

                            {% endfor %}
                        </section>

                    </div>
                    <div class="col-3 col-6-medium col-12-small">
                        <!-- Links -->
                        <section class="widget links">
                            <h3 style="color: white;">OUR BRANDS</h3>
                            {% for i in all_brands %}
                                <a href="http://{{ i.url }}">{{ i.name }}</a>
                            {% endfor %}
                        </section>

                    </div>
                    <div class="col-3 col-6-medium col-12-small">

                        <!-- Contact -->
                        <section class="widget links">
                            <h3 style="color: white;">CONTACT</h3>
                            <ul class="icons">
                                <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                                <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                                <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                                <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                                <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                            </ul>

                            <span style="color: white;">Tel:&nbsp;
                            <a>{{ com_message.tel }}</a>
                        </span>
                            <span style="color: white;">Email:&nbsp;
                             <a href="mailto:{{ com_message.email }}">{{ com_message.email }}</a>
                        </span>
                            <span style="color: white;">Website:&nbsp;
                            <a href="http://{{ com_message.web }}">{{ com_message.web }}</a>
                        </span>
                            <span style="color: white;">Address:&nbsp;</span>
                            <p style="color: #7e7e7e;">{{ com_message.addr }}</p>
                        </section>

                    </div>
                </div>

            </footer>
            <br><br><br>
            <div style="text-align: center;color: white;padding: auto auto;">
                    <span class="copyright">
                        &copy; 2019-2029.Tianjin Eternal Science and Technology Development Co. LTD.All rights reserved.
                    </span>
            </div>
        </div>
    </div>
{% endblock %}
{% block left-content %}{% endblock %}
{% block js %}
    <script src="{% static 'js/main_.js' %}"></script>
    <script>
        $(function () {
            $('.change_language').change(function (e) {
                e.preventDefault();
                $('#change_form').submit();
                return false;
            });
            $(document).ready(function () {
                $('#jsBtn').on('click', function () {
                    let name = $('#name').val();
                    let email = $('#email').val();
                    let country = $('#country').val();
                    let message = $('#message').val();
                    if (name === '' || email === '' || country === '' || message === '') {
                        alert('* Field is Required');
                        return;
                    }

                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "{% url 'company:contact' %}",
                        data: $('#jsForm').serialize(),
                        async: true,
                        success: function (data) {
                            if (data.status === 'success') {
                                $('#jsForm')[0].reset();
                                alert("{% trans 'We have received your message and will contact you as soon as possible.' %}")
                            } else if (data.status === 'fail') {
                                $('#jsCompanyTips').html(data.msg)
                            }
                        },
                    });
                });
            });
        })
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ index_info.title }}{% endblock %}
{% block description %}{{ index_info.description }}{% endblock %}
{% block keywords %}{{ index_info.keywords }}{% endblock %}